# Generated by Django 5.2.11 on 2026-03-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='data_plub',
            new_name='data_pub',
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.CharField(default=1, max_length=2, verbose_name='UF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da cidade'),
        ),
    ]
